create table if not exists public.recommendation_reports (
  id bigint generated by default as identity primary key,
  field_id text not null,
  generated_at timestamptz,
  county text,
  status text,
  forage text,
  weeds text[],
  livestock text,
  best_product text,
  backup_product text,
  engine_version text,
  guide_version text,
  pdf_path text,
  narrative text,
  inputs jsonb,
  result jsonb,
  created_at timestamptz not null default now()
);

create index if not exists recommendation_reports_field_id_idx
  on public.recommendation_reports (field_id);

create index if not exists recommendation_reports_county_idx
  on public.recommendation_reports (county);

create index if not exists recommendation_reports_generated_at_idx
  on public.recommendation_reports (generated_at);

insert into storage.buckets (id, name, public)
values ('extension-edge-reports', 'extension-edge-reports', false)
on conflict (id) do nothing;
